---
rhn_act_key: ezmeral

rhn_org_id: 15792716
 
required_packages:
- expect
- graphviz
- iptraf-ng
- krb5-workstation
- libatomic
- libcanberra-gtk2
- libibverbs
- libicu
- lm_sensors
- nfs-utils
- numactl
- PackageKit-gtk3-module
- xorg-x11-xauth
- bind-utils
- cairo
- libaio
- krb5-libs
- net-tools
- openssl
- rsyslog
- sudo
- xfsprogs
- gtk2
- libtool-ltdl
- iptraf-ng
- kbd
- kbd-legacy
- ndctl
- audispd-plugins


ntp_servers:
- 10.254.254.10
- 10.254.254.11
