---

- hosts: all
  gather_facts: true

  roles:
         - role: 01-selinux
           tags: 
             - role::os-preconfigure
             - role::os-preconfigure::selinux

         - role: 02-firewall
           tags:
             - role::os-preconfigure
             - role::os-preconfigure::firewall

         - role: 03-configure-issue
           tags:
             - role::os-preconfigure
             - role::os-preconfigure::configure-issue

         - role: 04-register-access-redhat
           tags:
             - role::os-preconfigure
             - role::os-preconfigure::register-access-redhat

         - role: 05-os-update
           tags:
             - role::os-preconfigure
             - role::os-preconfigure::os-update

         - role: 06-required-packages
           tags:
             - role::os-preconfigure
             - role::os-preconfigure::required-packages

         - role: 07-network-time-and-date2
           tags:
             - role::os-preconfigure
             - role::os-preconfigure::network-time-and-date

