---
- hosts: all
  gather_facts: true
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: ansible
    ansible_ssh_private_key_file: /opt/morpheus/.local/.ssh/id_rsa
  tasks:
     - name: Create test file
       file:
         path: /tmp/rtest
         state: touch
         mode: '0644'
         owner: root
         group: root

    



  