---
- hosts: all
  gather_facts: true
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: ansible
    ansible_ssh_private_key_file: /opt/morpheus/.local/.ssh/id_rsa
    #ansible_become_password: "{{ lookup('cypher','secret=password/ansible') }}"
  tasks:
      
   - name: Check DNS resolution for all cluster hosts
     shell: "timeout 480 nslookup {{ item }}"
     register: dns_check
     failed_when: dns_check.rc != 0
     loop: "{{ groups[morpheus['instance']['configGroup']] | default([]) }}"
     async: 480
     poll: 5
     delegate_to: localhost

  