---
- hosts: all
  gather_facts: true
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
    #ansible_user: ansible
    #ansible_ssh_private_key_file: /opt/morpheus/.local/.ssh/id_rsa
    #ansible_become_password: "{{ lookup('cypher','secret=password/ansible') }}"
  tasks:
     - name: Create test file
       file:
         path: /etc/example.conf
         state: touch
         mode: '0644'
         owner: root
         group: root
       when: ansible_facts['hostname'] == morpheus['instance']['name']
      
     - name: Hostname info
       shell: hostname
       register: hostname_output
       when: ansible_facts['hostname'] == morpheus['instance']['name']
    



  