---
- hosts: all
  gather_facts: true
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
    #ansible_user: ansible
    #ansible_ssh_private_key_file: /opt/morpheus/.local/.ssh/id_rsa
    #ansible_become_password: "{{ lookup('cypher','secret=password/ansible') }}"
  tasks:
     - name: get task1 result
       debug:
          msg: "{{ morpheus['results']['test1']['hostname_output'] }}"
       when: ansible_facts['hostname'] != morpheus['instance']['name']
    



  