---
- hosts: all
  gather_facts: true
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: hpe
    ansible_ssh_private_key_file: /opt/morpheus/.local/.ssh/id_rsa
  tasks:
     - name: Print hostname
       debug:
         msg: "dbHosts: {{ groups[mysql_tes] | join(', ') }}"

     - name: Debug inventory information
       debug:
         msg: 
          - "Current inventory_hostname: {{ inventory_hostname }}"
          - "ansible_fqdn: {{ ansible_fqdn }}"
          - "Instance Name: {{ morpheus['instance']['name'] }}"
          - "Host Name: {{ ansible_hostname }}"
       when: morpheus['instance']['name'] == ansible_hostname



  