---
- hosts: all
  gather_facts: true
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: ansible
    ansible_ssh_private_key_file: /opt/morpheus/.local/.ssh/id_rsa
    #ansible_become_password: "{{ lookup('cypher','secret=password/ansible') }}"
  tasks:
      
   - name: Write server info to /tmp
     copy:
       dest: "/tmp/server_info.txt"
       content: |
         Hostname: {{ ansible_hostname }}
         FQDN: {{ ansible_fqdn }}
         OS: {{ ansible_distribution }} {{ ansible_distribution_version }}
         Kernel: {{ ansible_kernel }}
         IP: {{ ansible_default_ipv4.address | default('N/A') }}
         CPU: {{ ansible_processor_vcpus }} vCPU
         RAM: {{ (ansible_memtotal_mb / 1024) | round(1) }} GB
