---
- hosts: all
  gather_facts: true
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: hpe
    ansible_ssh_private_key_file: /opt/morpheus/.local/.ssh/id_rsa
  roles:
       - role: 09-ubuntu-kubernetes-drain-node
         tags:
           - role::k8-drain-node
           - role::k8-teardown-worker-node::teardown-worker-node



  