---
- hosts: all
  gather_facts: true
  become: true
  roles:
       - role: 01-ubuntu-config-issue
         tags:
           - role::os-preconfigure
           - role::os-preconfigure::configure-issue