---
- hosts: all
  gather_facts: true
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: ansible
    ansible_ssh_private_key_file: /opt/morpheus/.local/.ssh/id_rsa
  roles:
       - role: 11-ubuntu-kubernetes-nfs-storage-class
         when: ansible_facts['hostname'] == morpheus['instance']['name']
         tags:
           - role::k8-master-node::nfs-storage-class 

       - role: 18-ubuntu-kubernetes-s3-storage-class
         when: ansible_facts['hostname'] == morpheus['instance']['name']
         tags:
           - role::k8-master-node::s3-storage-class  