---
- hosts: all
  gather_facts: true
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: ansible
    ansible_ssh_private_key_file: /opt/morpheus/.local/.ssh/id_rsa
  roles:
       - role: 01-ubuntu-config-issue
         tags:
           - role::os-preconfigure
           - role::os-preconfigure::configure-issue

       - role: 04-ubuntu-os-update
         tags:
           - role::os-preconfigure
           - role::os-preconfigure::os-upgrade

       - role: 15-ubuntu-minio-post-provision
         tags:
           - role::os-preconfigure
           - role::os-preconfigure::minio-requirements

       - role: 16-ubuntu-minio-conf
         tags:
           - role::minio-conf

       

        
