---
- hosts: all
  gather_facts: true
  become: true
  roles:
       - role: 07-ubuntu-kubernetes-initilize-cluster
         tags:
           - role::k8-master-node::initilize-cluster

       - role: 10-ubuntu-kubernetes-metalb-conf
         tags:
           - role::k8-master-node::metalb-conf  

  