---
- hosts: all
  gather_facts: true
  become: true
  roles:
       - role: 01-ubuntu-config-issue
         tags:
           - role::os-preconfigure
           - role::os-preconfigure::configure-issue

       - role: 02-ubuntu-swap-file
         tags:
           - role::os-preconfigure
           - role::os-preconfigure::swap-file

       - role: 03-ubuntu-ipv4-config
         tags:
           - role::os-preconfigure
           - role::os-preconfigure::ipv4-config

       - role: 04-ubuntu-os-update
         tags:
           - role::os-preconfigure
           - role::os-preconfigure::os-upgrade

       - role: 05-ubuntu-containerd-conf
         tags:
           - role::os-preconfigure
           - role::os-preconfigure::containerd-conf

       - role: 06-ubuntu-kubernetes-conf
         tags:
           - role::os-preconfigure
           - role::os-preconfigure::kubernetes-conf

       - role: 07-ubuntu-kubernetes-,initilize-cluster
         tags:
           - role::k8-master-node
           - role::k8-master-node::initilize-cluster

       #- role: 07-ubuntu-kubernetes-join-node
       #  tags:
       #    - role::k8-worker-node
       #    - role::k8-worker-node::kubernetes-join-node