---
- hosts: all
  gather_facts: true
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: hpe
    ansible_ssh_private_key_file: /opt/morpheus/.local/.ssh/id_rsa
  roles:
       - role: 08-ubuntu-kubernetes-join-node
         tags:
           - role::k8-worker-node
           - role::k8-worker-node::kubernetes-join-node



  