---
- hosts: all
  gather_facts: true
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: ansible
    ansible_ssh_private_key_file: /opt/morpheus/.local/.ssh/id_rsa
  roles:
       - role: 01-ubuntu-config-issue
         tags:
           - role::os-preconfigure
           - role::os-preconfigure::configure-issue

       - role: 04-ubuntu-os-update
         tags:
           - role::os-preconfigure
           - role::os-preconfigure::os-upgrade

       - role: 12-ubuntu-mysql-install
         tags:
           - role::mysql::install-mysql

       - role: 13-ubuntu-mysql-innodb-cluster
         tags:
           - role::mysql::inodb-cluster

       - role: 14-ubuntu-mysql-create-innodb-cluster
         when: ansible_facts['hostname'] == morpheus['instance']['name']
         tags:
           - role::mysql::inodb-cluster

        
