---
- hosts: all
  gather_facts: true
  become: true
  roles:
       - role: 09-ubuntu-kubernetes-drain-node
         tags:
           - role::k8-drain-node
           - role::k8-drain-node::teardown-worker-node



  