---
- hosts: all
  gather_facts: true
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: ansible
    ansible_ssh_private_key_file: /opt/morpheus/.local/.ssh/id_rsa
  roles:
       - role: 06-ubuntu-kubernetes-conf
         when: ansible_facts['hostname'] == morpheus['instance']['name']
         tags:
           - role::os-preconfigure
           - role::os-preconfigure::kubernetes-conf
           
       - role: 07-ubuntu-kubernetes-initilize-cluster
         when: ansible_facts['hostname'] == morpheus['instance']['name']
         tags:
           - role::k8-master-node::initilize-cluster
  