---

- name: get join command
  shell: kubeadm token create --print-join-command
  register: join_command_raw
  delegate_to: "{{ groups['kubernetes-master'][0] }}"

- name: set join command
  set_fact:
    join_command: "{{ join_command_raw.stdout_lines[0] }}"

- name: join cluster
  shell: "{{ join_command }} --ignore-preflight-errors all  >> node_joined.txt"
  args:
    chdir: $HOME
    creates: node_joined.txt
