---

- name: Check if node is already part of a cluster
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubelet_conf

- name: Join and label kubernetes node block
  block:
    - name: join kubernetes cluster
      shell: "kubeadm join {{ morpheus['customOptions']['k8_master_ip'] }}:6443 --token {{ lookup('cypher','secret=secret/K8-join-token') }} --discovery-token-ca-cert-hash {{ lookup('cypher','secret=secret/K8-join-token-ca-cert-hash') }}"
      register: join_result

    - name: Kubernetes Cluster Node Join Result
      debug:
        var: join_result.stdout_lines

    - name: Wait for node to be ready
      pause:
        seconds: 30

  when: not kubelet_conf.stat.exists


- name: Label node as worker
  kubernetes.core.k8s:
      api_version: v1
      kind: Node
      name: "{{ ansible_hostname }}"
      definition:
        metadata:
          labels:
            node-role.kubernetes.io/worker: "worker"
  register: label_result
  delegate_to: k8master
  #delegate_to: "{{ morpheus['customOptions']['k8_master_ip'] }}"
  vars:
  #  ansible_user: emre.baykal
    ansible_user: morpheus-node
    ansible_ssh_private_key_file: /opt/morpheus/.local/.ssh/id_ed25519

- name: Show label result
  debug:
      var: label_result

