---
# vars file for redhat-os-preconfigure

sap_required_packages:
- expect
- graphviz
- iptraf-ng
- krb5-workstation
- libatomic
- libcanberra-gtk2
- libibverbs
- libicu
- lm_sensors
- nfs-utils
- numactl
- PackageKit-gtk3-module
- xorg-x11-xauth
- bind-utils
- cairo
- libaio
- krb5-libs
- net-tools
- openssl
- rsyslog
- sudo
- xfsprogs
- gtk2
- libtool-ltdl
- tuned-profiles-sap-hana
- compat-sap-c++-12
- iptraf-ng
- kbd
- kbd-legacy
- ndctl
- audispd-plugins
