---

- name: Check Current Status Of FIPS Mode
  command: /usr/bin/fips-mode-setup --check
  register: is_fips_enabled
  changed_when: false
  failed_when: false

- name: Enable Federal Information Processing Standard (FIPS MODE)
  block:  
    - name: Excute Command To Enable FIPS mode
      command: /usr/bin/fips-mode-setup --enable
    
    - name: Enable Dracut FIPS Module
      lineinfile:
        path: /etc/dracut.conf.d/40-fips.conf
        line: add_dracutmodules+=" fips "

    - name: Rebooting ...
      shell: sleep 2 && /sbin/shutdown -r now "Reboot required for updated kernel"
      async: 1
      poll: 0
      ignore_errors: true
      register: rebooting

    - name: Wait for system to become reachable
      wait_for_connection:
        timeout: 900
        sleep: 15
        delay: 30
      when: rebooting.changed

  when: is_fips_enabled.stdout.find('FIPS mode is enabled.') == -1

- name: Install Required Packages For Use Strong Crypto Policies
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - crypto-policies
    - gnutls-utils
    - nss-tools
    - rng-tools