---

- name: Adjust sysctl variables to improve network security
  sysctl:
    name="{{ item.pname }}"
    value="{{ item.value }}"
    sysctl_set=yes
    state=present
    reload=yes
  with_items:
   - { pname: 'net.ipv4.conf.default.rp_filter', value: '1'}
   - { pname: 'net.ipv4.conf.all.rp_filter', value: '1'}
   - { pname: 'net.ipv4.conf.default.accept_source_route', value: '0'}
   - { pname: 'net.ipv4.conf.all.accept_source_route', value: '0'}
   - { pname: 'net.ipv4.tcp_syncookies', value: '1'}
   - { pname: 'net.ipv4.icmp_echo_ignore_broadcasts', value: '1'}
   - { pname: 'net.ipv4.icmp_ignore_bogus_error_responses', value: '1'}
   - { pname: 'net.ipv4.conf.default.secure_redirects', value: '0'}
   - { pname: 'net.ipv4.conf.all.secure_redirects', value: '0'}
   - { pname: 'net.ipv4.conf.default.accept_redirects', value: '0'}
   - { pname: 'net.ipv4.conf.all.accept_redirects', value: '0'}
   - { pname: 'net.ipv4.tcp_max_syn_backlog', value: '4096'}
   - { pname: 'net.ipv4.ip_forward', value: '0'}
   - { pname: 'net.ipv4.conf.default.send_redirects', value: '0'}
   - { pname: 'net.ipv4.conf.all.send_redirects', value: '0'}
   - { pname: 'fs.inotify.max_user_watches', value: '65536'}
   - { pname: 'net.ipv4.conf.default.promote_secondaries', value: '1'}
   - { pname: 'net.ipv4.conf.all.promote_secondaries', value: '1'}

