---
- name: Deploy isse.net file to the clients
  template:
    src=files/issue.net
    dest=/etc/issue.net
    owner=root
    group=root
    mode=0644
    backup=yes
  notify: restart_ssh_client

- name: Set Banner in sshd_config
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?Banner'
    line: 'Banner /etc/issue.net'
    state: present
  notify: restart_ssh_client

- name: Force all notified SSH services
  meta: flush_handlers