---
- name: Update apt package index
  apt:
    update_cache: yes

- name: Install required packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gpg
    state: present

- name: Create directory for apt keyrings
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Kubernetes GPG key
  apt_key:
    url: "https://pkgs.k8s.io/core:/stable:/v{{ morpheus['customOptions']['kubernetes_vers'] }}/deb/Release.key"
    state: present
    keyring: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Add Kubernetes repository to apt sources
  apt_repository:
    filename: kubernetes
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v{{ morpheus['customOptions']['kubernetes_vers'] }}/deb/ /"
    state: present
  notify: update-apt-package

- name: Install Kubernetes Packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - kubelet
    - kubeadm
    - kubectl
    