---
# tasks file for network-time-and-date

- name: Populate service facts
  service_facts:

- name: Adjust Default clock settings
  command: "timedatectl set-timezone Europe/Istanbul"
  when: ansible_facts.services["chronyd.service"].state == "inactive"

- name: Delete default pool config
  lineinfile:
     path: /etc/chrony.conf
     regexp: "^pool*." 
     state: absent

- name: Set NTP server via chrony
  lineinfile:
     dest: /etc/chrony.conf
     line: "server {{ item }} iburst"
  with_items: "{{ ntp_servers }}"

- name: Optimize For Microsoft Windows NP Servers
  lineinfile:
     dest: /etc/chrony.conf
     line: maxdistance 16.0

- name: Start Chronyd
  command: "{{item}}"
  with_items:
  - systemctl restart chronyd
  - systemctl enable chronyd

