# Enable IPv4 packet forwarding  
--- 
- name: Set sysctl parameters for Kubernetes
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.ipv4.ip_forward = 1
  notify: apply-sysctl-parameters

- name: Create modules-load configuration for containerd
  copy:
    dest: /etc/modules-load.d/containerd.conf
    content: |
      br_netfilter
  notify: load-br_netfilter-module

- name: Flush handlers
  meta: flush_handlers

- name: Apply sysctl parameters from /etc/sysctl.conf
  command: sysctl -p /etc/sysctl.conf

  