# Enable IPv4 packet forwarding  
--- 
    - name: Set sysctl parameters for Kubernetes
      copy:
        dest: /etc/sysctl.d/k8s.conf
        content: |
          net.ipv4.ip_forward = 1

    - name: Apply sysctl parameters without reboot
      command: sysctl --system

    - name: Create modules-load configuration for containerd
      copy:
        dest: /etc/modules-load.d/containerd.conf
        content: |
          br_netfilter

    - name: Load br_netfilter module
      command: modprobe br_netfilter

    - name: Apply sysctl parameters from /etc/sysctl.conf
      command: sysctl -p /etc/sysctl.conf