- name: Check if swapfile exists
  stat:
    path: /swap.img
  register: swapfile

- block:
    - name: Disable swap
      command: swapoff /swap.img

    - name: Remove swapfile entry from /etc/fstab
      lineinfile:
        path: /etc/fstab
        state: absent
        regexp: '^/swap.img'

    - name: Remove the swapfile
      file:
        path: /swap.img
        state: absent
  when: swapfile.stat.exists
