---
- name: Configure /etc/issue.net file
  copy:
    dest: /etc/issue.net
    content: |
      Welcome to {{ ansible_hostname }}
      Authorized access only!
      All activities may be monitored and reported.

- name: Set Banner in sshd_config
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?Banner'
    line: 'Banner /etc/issue.net'
    state: present
  notify: restart_ssh_client

- name: Force all notified SSH services
  meta: flush_handlers