---
# handlers file for suse-os-preconfigure

  - name: restart_chronyd
    command: "{{item}}"
    with_items:
    - systemctl start chronyd
    - systemctl enable chronyd

  - name: restart_ssh_client
    command: "{{item}}"
    with_items:
    - systemctl restart sshd

  - name: restart_timesyncd
    command: systemctl restart systemd-timesyncd.service
