---

- name: Gathering service facts
  service_facts:
  register: services_state

- name: Disable Automounting
  service:
    name: autofs
    state: stopped
    enabled: no
  when: services_state.ansible_facts.services["autofs.service"]|default

