---

- name: Ensure PAM variable minlen is set accordingly
  lineinfile:
    create: true
    dest: /etc/security/pwquality.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
     - { line: 'minlen = 8', regexp: '^#?\s*minlen'}
     - { line: 'minclass = 4', regexp: '^#?\s*minclass'}
     - { line: 'lcredit = -1', regexp: '^#?\s*lcredit'}
     - { line: 'ucredit = -1', regexp: '^#?\s*ucredit'}
     - { line: 'dcredit = -1', regexp: '^#?\s*dcredit'}
     - { line: 'ocredit = 0', regexp: '^#?\s*ocredit'}
     - { line: 'difok = 5', regexp: '^#?\s*difok'}

- name: Set Password Retry Prompts Permitted Per-Session - system-auth (change)
  replace:
    dest: /etc/pam.d/system-auth
    regexp: (^.*\spam_pwquality.so\s.*retry\s*=\s*)(\S+)(.*$)
    replace: \g<1>3\g<3>


- name: Set Password Retry Prompts Permitted Per-Session - system-auth (add)
  replace:
    dest: /etc/pam.d/system-auth
    regexp: ^.*\spam_pwquality.so\s(?!.*retry\s*=\s*).*$
    replace: \g<0> retry=3

- name: Do not allow users to reuse recent passwords - system-auth (change)
  replace:
   dest: /etc/pam.d/system-auth
   regexp: ^(password\s+sufficient\s+pam_unix\.so\s.*remember\s*=\s*)(\S+)(.*)$
   replace: \g<1>5\g<3>


- name: Do not allow users to reuse recent passwords - system-auth (add)
  replace:
   dest: /etc/pam.d/system-auth
   regexp: ^password\s+sufficient\s+pam_unix\.so\s(?!.*remember\s*=\s*).*$
   replace: \g<0> remember=5


- name: Set Password Hashing Algorithm in /etc/libuser.conf
  lineinfile:
    dest: /etc/libuser.conf
    insertafter: ^\s*\[defaults]
    regexp: ^#?crypt_style
    line: crypt_style = sha512
    state: present

- name: Set Password Hashing Algorithm in /etc/login.defs
  lineinfile:
    dest: /etc/login.defs
    regexp: ^#?ENCRYPT_METHOD
    line: ENCRYPT_METHOD SHA512
    state: present


- name: /etc/login.defs - Ensure SHA_CRYPT_MAX_ROUNDS has Minimum Value of 5000
  lineinfile:
    dest: /etc/login.defs
    regexp: ^#?#SHA_CRYPT_MAX_ROUNDS
    line: SHA_CRYPT_MAX_ROUNDS 5000
    state: present

