---
# tasks file for os-security-hardening
##

  - import_tasks: 01-enable-fips-mode.yml
    tags:
      - role::os-security-hardening
      - role::os-security-hardening::enable-fips-mode
    when:
      - ansible_distribution_major_version == "9"
      - fips_mode == true

  - import_tasks: 02-disable-automount.yml
    tags:
      - role::os-security-hardening
      - role::os-security-hardening::disable-automount

  - import_tasks: 03-disable-usb-mass-storage.yml
    tags:
      - role::os-security-hardening
      - role::os-security-hardening::disable-usb-mass-storage

  - import_tasks: 04-ssh-client-security.yml
    tags:
      - role::os-security-hardening
      - role::os-security-hardening::ssh-client-security

  - import_tasks: 05-postfix-config.yml
    tags:
      - role::os-security-hardening
      - role::os-security-hardening::postfix-config

  - import_tasks: 06-disable-ctrl-alt-delete.yml
    tags:
      - role::os-security-hardening
      - role::os-security-hardening::disable-ctrl-alt-delete
  
  - import_tasks: 07-cronjobs-hardening.yml
    tags:
      - role::os-security-hardening
      - role::os-security-hardening::cronjobs-hardening

  - import_tasks: 08-restrict-sudo.yml
    tags:
      - role::os-security-hardening
      - role::os-security-hardening::restrict-sudo

  - import_tasks: 09-login-definitions.yml
    tags:
      - role::os-security-hardening
      - role::os-security-hardening::login-definitions

  - import_tasks: 10-create-operator-user.yml
    tags:
      - role::os-security-hardening
      - role::os-security-hardening::create-operator-user

  - import_tasks: 11-password-strength.yml
    tags:
      - role::os-security-hardening
      - role::os-security-hardening::password-srength

  - import_tasks: 12-improve-network-security.yml
    tags:
      - role::os-security-hardening
      - role::os-security-hardening::improve-network-security

  - import_tasks: 13-configure-audit-log.yml
    tags:
      - role::os-security-hardening
      - role::os-security-hardening::configure-audit-log
