---
- name: Stop AppArmor service
  systemd:
    name: apparmor
    state: stopped


- name: Disable AppArmor service
  systemd:
    name: apparmor
    enabled: no

- name: Copy mysql-apt-config package to the target machine
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "/tmp/{{ item }}"
  with_items:
    - mysql-apt-config_0.8.33-1_all.deb

- name: Install mysql-apt-config package
  apt:
    deb: /tmp/mysql-apt-config_0.8.33-1_all.deb
    state: present

- name: Update apt cache
  apt:
    update_cache: yes

- name: Installing Mysql
  package:
      name: "{{item}}"
      state: present
      update_cache: yes
  loop:
    - mysql-server
    - mysql-client
    - python3-mysqldb
    - libmysqlclient-dev


- name: Ensure MySQL service is started and enabled
  systemd:
    name: mysql
    state: started
    enabled: yes

- name: Hold MySQL server package version
  dpkg_selections:
    name: mysql-server
    selection: hold

- name: Create MySQL native password configuration file
  copy:
    dest: /etc/mysql/conf.d/enable-mysql-native-password.cnf
    content: |
      [mysqld]
      mysql_native_password=ON
    owner: root
    group: root
    mode: '0644'
  notify:
      - Restart mysql

- name: Flush handlers
  meta: flush_handlers

#- name: Set root user password
#  mysql_user:
#    name: root
#    password: "{{root_password}}"
#    login_unix_socket: /var/run/mysqld/mysqld.sock
#    host: localhost
#    login_user: root
#    login_password: ''
#    state: present

- name: Create admin user with remote access
  mysql_user:
    name: "{{admin_user}}"
    password: "{{admin_password}}"
    priv: '*.*:ALL'
    host: '%'
    append_privs: yes
    login_user: root
    login_password: "{{root_password}}"
    state: present

- name: Delete blank users
  mysql_query:
    query: "DELETE FROM mysql.user WHERE User='';"
    login_user: root
    login_password: "{{root_password}}"

- name: Delete test database
  mysql_db:
    name: test
    state: absent
    login_user: root
    login_password: "{{root_password}}"

- name: Delete references to test database
  mysql_query:
    query: "DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%';"
    login_user: root
    login_password: "{{root_password}}"

- name: Set invisible primary key
  mysql_query:
    query: "SET PERSIST sql_generate_invisible_primary_key=1;"
    login_user: root
    login_password: "{{root_password}}"

- name: Create MySQL InnoDB configuration file
  copy:
    dest: /etc/mysql/mysql.conf.d/innodb-mysqld.cnf
    content: |
      [mysqld]
      bind-address = 0.0.0.0
      max_connections = 451
      innodb_buffer_pool_size=6G
      innodb_buffer_poolinstances=6
      innodb_use_fdatasync=ON
      sql_generate_invisible_primary_key=1
      binlog_expire_logs_seconds=604800
      binlog_expire_logs_auto_purge=ON

      [mysqldump]
      set-gtid-purged=OFF
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart mysql

- name: Flush handlers
  meta: flush_handlers

- name: Install mysqlSHELL
  package:
      name: mysql-shell
      state: present
      update_cache: yes