---
- name: Stop AppArmor service
  systemd:
    name: apparmor
    state: stopped


- name: Disable AppArmor service
  systemd:
    name: apparmor
    enabled: no

- name: Copy mysql-apt-config package to the target machine
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "/tmp/{{ item }}"
  with_items:
    - mysql-apt-config_0.8.33-1_all.deb
    - mysql-apt-config_0.8.33-1_all.deb.asc

- name: Install mysql-apt-config package
  apt:
    deb: /tmp/mysql-apt-config_0.8.33-1_all.deb
    state: present

#- name: Import MySQL GPG key
#  apt_key:
#    file: /tmp/mysql-apt-config_0.8.33-1_all.deb.asc
#    state: present
#    validate_certs: no

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install MySQL server and shell
  apt:
    name:
      - mysql-server
      - mysql-shell
    state: present

- name: Ensure MySQL service is started and enabled
  systemd:
    name: mysql
    state: started
    enabled: yes

- name: Hold MySQL server package version
  dpkg_selections:
    name: mysql-server
    selection: hold