---
- name: Stop AppArmor service
  systemd:
    name: apparmor
    state: stopped


- name: Disable AppArmor service
  systemd:
    name: apparmor
    enabled: no

- name: Copy mysql-apt-config package to the target machine
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "/tmp/{{ item }}"
  with_items:
    - mysql-apt-config_0.8.33-1_all.deb

- name: Install mysql-apt-config package
  apt:
    deb: /tmp/mysql-apt-config_0.8.33-1_all.deb
    state: present

- name: Update apt cache
  apt:
    update_cache: yes

- name: Installing Mysql
  package:
      name: "{{item}}"
      state: present
      update_cache: yes
  loop:
    - mysql-server
    - mysql-client
    - mysql-shell
    - python3-mysqldb
    - libmysqlclient-dev


- name: Ensure MySQL service is started and enabled
  systemd:
    name: mysql
    state: started
    enabled: yes

- name: Hold MySQL server package version
  dpkg_selections:
    name: mysql-server
    selection: hold

- name: Create MySQL native password configuration file
  copy:
    dest: /etc/mysql/conf.d/enable-mysql-native-password.cnf
    content: |
      [mysqld]
      mysql_native_password=ON
    owner: root
    group: root
    mode: '0644'
  notify:
      - Restart mysql_service

- name: Flush handlers
  meta: flush_handlers

- name: Set root user password
  mysql_user:
    name: root
    # password: "{{root_password}}"
    password: "{{ morpheus['customOptions']['mysql_root_password'] }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    host: localhost
    login_user: root
    login_password: ''
    state: present

