---

  - name: Disable Firewalld
    service:
      name: firewalld
      state: stopped
      enabled: no

  - name: Disable Selinux
    selinux:
      state: disabled
    register: selinux_state

  - name: Rebooting ...
    shell: sleep 2 && /sbin/shutdown -r now "Reboot required for updated kernel"
    async: 1
    poll: 0
    ignore_errors: true
    when: selinux_state.reboot_required == True
    register: rebooting

  - name: Wait for system to become reachable
    wait_for_connection:
      timeout: 900
      sleep: 15
      delay: 30
    when: rebooting.changed

