---

- name: Change Banner Parameters to /etc/ssh/sshd_config
  replace:
      path=/etc/ssh/sshd_config
      regexp='^#Banner none'
      replace='Banner /etc/issue.net'


- name: Deploy isse.net file to the clients
  template:
    src=files/issue.net
    dest=/etc/issue.net
    owner=root
    group=root
    mode=0644
    backup=yes
  notify: restart_ssh_client

- name: Force all notified SSHD services
  meta: flush_handlers
