---

 - name: Install yum utils package
   dnf:
    name: yum-utils
    state: present

 - name: Update Latest Operating System Patch
   dnf:
    name: '*'
    state: latest

 - name: Check for reboot hint.
   command: needs-restarting -r
   no_log: true
   #ignore_errors: true
   register: reboot_hint
   failed_when: reboot_hint.rc >= 2

 - name: Rebooting ...
   shell: sleep 2 && /sbin/shutdown -r now "Reboot required for updated kernel"
   async: 1
   poll: 0
   ignore_errors: true
   when: reboot_hint.rc == 1
   register: rebooting

 - name: Wait for system to become reachable
   wait_for_connection:
     timeout: 900
     sleep: 15
     delay: 30
   when: rebooting.changed

