---
- name: Create MinIO environment configuration file
  template:
    src: minio.j2
    dest: /etc/default/minio
    owner: root
    group: root
    mode: '0644'

- name: Update minio.service file with the required changes
  lineinfile:
    path: /tmp/minio.service.j2
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^WorkingDirectory=/usr/local$', line: 'WorkingDirectory=/opt/minio' }
    - { regexp: '^User=minio-user$', line: 'User=minio' }
    - { regexp: '^Group=minio-user$', line: 'Group=minio' }
    - { regexp: '^EnvironmentFile=-/etc/default/minio$', line: 'EnvironmentFile=/etc/default/minio' }
  notify: minio-service

- name: Flush handlers
  meta: flush_handlers

- name: Check MinIO service status
  command: systemctl status minio
  register: minio_status
  changed_when: false
  failed_when: false

- name: Display MinIO service status
  debug:
    var: minio_status.stdout_lines

- name: Check listening ports
  shell: ss -tuln | grep -E ':9000|:9001'
  register: port_check
  changed_when: false
  failed_when: false

- name: Display listening ports
  debug:
    var: port_check.stdout_lines

