---
# tasks file for register-access-redhat
#
  - name: Subscription Pre-Registration
    shell: "subscription-manager status | grep Unknown | wc -l"
    changed_when: False
    register: subscription

  - name: RHN Subscription
    block:

    - name: Check connectivity https://access.redhat.com and it returns a status 200
      uri:
        url: https://access.redhat.com
        status_code: 200

    - name: Register Servers To the access.redhat.com site
      redhat_subscription:
        state: present
        activationkey: "{{ rhn_act_key }}"
        org_id: "{{ rhn_org_id }}"

    when:
     - subscription.stdout|int >= 1
